baseURL = "https://ningonone.github.io"
languageCode = "zh-CN"
title = "ningonone's blog"
theme = "yinyang"

[params]
# disqus = "joway" # disqus account name
headTitle = "NINGO" 
description = "store some memories here..." 
extraHead = ''
mainSections = ["posts"]
galleryPassword = "106078"
favicon = "/images/avatar.png"
showToc = true

[[params.socials]]
name = "Post"
link = "/index.html"

[[params.socials]]
name = "Movies"
link = "/pages/movies/"


[[params.socials]]
name = "Gallery"
link = "/pages/gallery/"
