# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
  - cron: '0 0 * * *'

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: NINGO404
        type: movie
        format: csv
        dir: ./assets
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './assets'
        
    - name: Trigger Hugo Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        event-type: hugo-update
