name: Deploy Hugo Site to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
permissions:
  contents: read
  pages: write
  id-token: write  # 确保包含这一行
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true  # 如果使用了 Hugo 主题作为子模块，需要启用递归
          fetch-depth: 0    # 获取完整的 Git 历史记录

      # 2. 安装 Hugo Extended
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'  # 使用最新版本
          extended: true          # 使用扩展版

      # 3. 构建 Hugo 站点
      - name: Build Hugo site
        run: hugo --minify

      # 4. 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
